---
title: "Wild Git Collaboration Practice"
format: 
  html:
    code-fold: show
execute: 
  warning: false
  message: false
---
```{r}

library(ggplot2)
library(tidyverse)

```


## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)


diamond_clean <- diamonds |>
  clean_names()


diamonds_plot <- ggplot(diamond_clean)+
  geom_point(aes(x=carat,y=price))



```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"

diamonds_df <- diamonds

diamonds_subset_df <- diamonds_df |>
  filter(carat > 1) |>
  filter(cut == "Ideal")



```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```

